apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: myapp
data:
  PORT: "3000"
  NODE_ENV: "production"
  SUPABASE_URL: "https://ysqqejpjxvjdnmmrloja.supabase.co""
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: myapp
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:@l0h0m0rA-supabase14@db.ysqqejpjxvjdnmmrloja.supabase.co:5432/postgres"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzcXFlanBqeHZqZG5tbXJsb2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1MTMzNjIsImV4cCI6MjA5NDA4OTM2Mn0.FBPJ2vRpTtcype_C_fd8kNwiSjbOHcWnU1tTd7hMzao" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: myapp
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: gumi236/moodflix-v2:d4d4a81
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: myapp
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
